services:
  champsim:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount specific directories for data persistence
      - ./ChampSim/traces:/app/ChampSim/traces
      - ./ChampSim/results:/app/ChampSim/results
      - ./ChampSim/prefetch_files:/app/ChampSim/prefetch_files
      - ./ChampSim/model.py:/app/ChampSim/model.py
      - ./ChampSim/autorunCFlite.sh:/app/ChampSim/autorunCFlite.sh
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    # Memory configuration compatible with latest Docker Compose
    deploy:
      resources:
        limits:
          memory: 13G
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]